### ISSUE TITLE
Investigate colour/palette

### ISSUE THREAD

**Issue by olimj** [ones-own/ones-own-website#4]

**Comment by jeddy3** [comment]
[Color within Constraints - A scalable color system for digital products](https://medium.com/tap-to-dismiss/color-within-constraints-d6f777a3b72d):

> Build a more rigid system if color usage can be clearly documented and there are very few use cases that currently break the system.

[Respecting user preferences](https://www.matuzo.at/blog/writing-even-more-css-with-accessibility-in-mind-user-preferences/#dark-mode)

> Change the design according to user preference but allow users to change it back.

> Some users may prefer a dark theme for the OS but light themes on the web. They should be able to pick their preferred theme.

**Comment by jeddy3** [comment]
[Making dark theme switcher with PostCSS.](https://equinusocio.dev/blog/making-dark-theme-switcher-with-postcss/):

> A very simple theme switcher should offer at least 3 options:
> - Dark theme
> - Light theme
> - Automatic theme (should be on by default)
