### ISSUE TITLE
Readability/rendering of font

### ISSUE THREAD

**Issue by olimj** [ones-own/ones-own-website#5]

**Comment by jeddy3** [comment]
[Respecting user preferences](https://www.matuzo.at/blog/writing-even-more-css-with-accessibility-in-mind-user-preferences/#font-size):

> A fundamental thing we should do is respect our users’ preferred font size for running text

[Clamp](https://utopia.fyi/blog/clamp/):

> CSS has some exciting new features for fluid scaling.

[Accessibility - Viewport scale](https://design-system.barnardos.org.uk/standards/viewport-scale/)

> The layout and type can be proportionally scaled to maintain an optimal line length at any viewport size.
